backend:
  name: git-gateway
  branch: main   # or master if that is your default branch
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "mods"
    label: "Free Mods"
    folder: "mods"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "YouTube Link", name: "youtube", widget: "string" }
      - { label: "Screenshot", name: "screenshot", widget: "image" }
      - { label: "Download Link", name: "download", widget: "string" }
